# Generated by Django 3.2.9 on 2021-11-19 17:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='location uuid', primary_key=True, serialize=False, verbose_name='location uuid')),
                ('name', models.CharField(max_length=20, verbose_name='location name')),
                ('place_id', models.CharField(max_length=20, verbose_name='GoogleMap place ID')),
                ('lat', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='GoogleMap place lat')),
                ('lng', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='GoogleMap place lng')),
                ('is_startPlace', models.BooleanField(default=False, verbose_name='start location')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'location',
                'db_table': 'Place_info',
            },
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='location uuid', primary_key=True, serialize=False, verbose_name='location uuid')),
                ('distance', models.FloatField(verbose_name='distance')),
                ('travelTime', models.IntegerField(verbose_name='travelTime')),
                ('endPlace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endPlace', to='logistic_solution.place')),
                ('startPlace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startplace', to='logistic_solution.place')),
            ],
        ),
    ]
