# Generated by Django 3.2.9 on 2021-11-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_solution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.DecimalField(decimal_places=10, max_digits=15, verbose_name='GoogleMap place lng'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.CharField(max_length=50, verbose_name='GoogleMap place ID'),
        ),
    ]
