# Generated by Django 3.2.9 on 2021-11-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_solution', '0002_auto_20211119_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.DecimalField(decimal_places=10, max_digits=15, verbose_name='GoogleMap place lat'),
        ),
    ]
