# Generated by Django 3.2.9 on 2021-11-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_solution', '0003_alter_place_lat'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='score',
            field=models.IntegerField(default=5, verbose_name='score'),
            preserve_default=False,
        ),
    ]
