# Generated by Django 3.2.9 on 2021-11-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_solution', '0005_alter_place_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path',
            name='travelTime',
        ),
        migrations.AddField(
            model_name='path',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='duration'),
        ),
    ]
