# Generated by Django 3.2.9 on 2021-11-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic_solution', '0006_auto_20211120_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='distance',
            field=models.CharField(max_length=20, verbose_name='distance'),
        ),
        migrations.AlterField(
            model_name='path',
            name='duration',
            field=models.CharField(default=0, max_length=20, verbose_name='duration'),
        ),
    ]
