{'bounds':
     {'northeast': {'lat': 22.4198668, 'lng': 114.2108369},
      'southwest': {'lat': 22.3788513, 'lng': 114.1870296}},
  'copyrights': 'Map data ©2021',
  'legs':
        [{'distance': {'text': '7.2 km', 'value': 7224},
          'duration': {'text': '15 mins', 'value': 925},
          'duration_in_traffic': {'text': '15 mins', 'value': 915},
          'end_address': 'The Chinese University of Hong Kong, Central Ave, Ma Liu Shui, Hong Kong',
          'end_location': {'lat': 22.4198641, 'lng': 114.2067573},
          'start_address': '18 Sha Tin Centre St, Sha Tin, Hong Kong',
          'start_location': {'lat': 22.3817739, 'lng': 114.1886178},
          'steps':
              [{'distance': {'text': '48 m', 'value': 48},
                'duration': {'text': '1 min', 'value': 26},
                'end_location': {'lat': 22.3816007, 'lng': 114.1882194},
                'html_instructions': 'Head <b>southwest</b> toward <b>Sha Tin Centre St</b>',
                'polyline': {'points': 'amrgC{m}wT@@TTF\\@X'},
                'start_location': {'lat': 22.3817739, 'lng': 114.1886178},
                'travel_mode': 'DRIVING'},
               {'distance': {'text': '0.1 km', 'value': 104},
                'duration': {'text': '1 min', 'value': 33},
                'end_location': {'lat': 22.3808279, 'lng': 114.1877356},
                'html_instructions': 'Turn <b>left</b> onto <b>Sha Tin Centre St</b>',
                'maneuver': 'turn-left', 'polyline': {'points': '_lrgCkk}wTvArA@@DBDBB@H@F@H?RC'},
                'start_location': {'lat': 22.3816007, 'lng': 114.1882194}, 'travel_mode': 'DRIVING'},
               {'distance': {'text': '0.3 km', 'value': 271},
                'duration': {'text': '1 min', 'value': 39},
                'end_location': {'lat': 22.3788513, 'lng': 114.1875601},
                'html_instructions': 'Merge onto <b>Pak Hok Ting St</b>',
                'maneuver': 'merge', 'polyline': {'points': 'egrgCkh}wTpB[pAWjB_@TCFAD?D@D@DBBBDF@BDDR~A'},
                'start_location': {'lat': 22.3808279, 'lng': 114.1877356}, 'travel_mode': 'DRIVING'},
               {'distance': {'text': '0.6 km', 'value': 617},
                'duration': {'text': '2 mins', 'value': 130},
                'end_location': {'lat': 22.3833537, 'lng': 114.1897155},
                'html_instructions': 'Turn <b>right</b> onto <b>Sha Tin Centre St</b>',
                'maneuver': 'turn-right',
                'polyline': {'points': 'yzqgCgg}wTMREFQJE?AAC@C?C?C?C@C@G@eCd@q@NM@c@BSCGCKEOMi@k@qBoBaEsDYYaAw@qAmACAACAG'},
                'start_location': {'lat': 22.3788513, 'lng': 114.1875601},
                'travel_mode': 'DRIVING'},
               {'distance': {'text': '0.2 km', 'value': 180},
                'duration': {'text': '1 min', 'value': 37},
                'end_location': {'lat': 22.3823204, 'lng': 114.1910536},
                'html_instructions': 'Turn <b>right</b> onto <b>Wang Pok St</b>',
                'maneuver': 'turn-right', 'polyline': {'points': '}vrgCwt}wT?G?C@CNSX_@z@kAV]X[f@q@JM'},
                'start_location': {'lat': 22.3833537, 'lng': 114.1897155}, 'travel_mode': 'DRIVING'},
               {'distance': {'text': '0.1 km', 'value': 99},
                'duration': {'text': '1 min', 'value': 26},
                'end_location': {'lat': 22.3828471, 'lng': 114.1917657},
                'html_instructions': 'Turn <b>left</b> to stay on <b>Wang Pok St</b>',
                'maneuver': 'turn-left', 'polyline': {'points': 'oprgCa}}wTCg@?ECECE_@[m@k@GEGG'},
                'start_location': {'lat': 22.3823204, 'lng': 114.1910536}, 'travel_mode': 'DRIVING'},
               {'distance': {'text': '0.3 km', 'value': 334},
                'duration': {'text': '1 min', 'value': 71},
                'end_location': {'lat': 22.3848622, 'lng': 114.1893535},
                'html_instructions': 'Turn <b>left</b> at the 1st cross street onto <b>Sha Tin Rural Committee Rd</b>',
                'maneuver': 'turn-left',
                'polyline': {'points': 'ysrgCqa~wTQTaBpB_AhAY^kAzA_@d@ORMPEHk@t@GH'},
                'start_location': {'lat': 22.3828471, 'lng': 114.1917657},
                'travel_mode': 'DRIVING'},
               {'distance': {'text': '2.5 km', 'value': 2466},
                'duration': {'text': '3 mins', 'value': 151},
                'end_location': {'lat': 22.4018035, 'lng': 114.204041},
                'html_instructions': 'Turn <b>right</b> to merge onto <b>New Territories Circular Rd</b>/<wbr/><b>Tai Po Road (Sha Tin)</b>',
                'maneuver': 'ramp-right',
                'polyline': {'points': 'k`sgCmr}wTQOOGECaBsA_@[SOg@a@UUGEKK{@w@YWAAAAAEEOWSm@i@YUYYg@e@aBgB_AcAi@m@aAiAqBcCk@o@k@w@w@eA_@m@MQEIUe@]s@k@uAe@mAKYQ_@EKo@yA]u@Wk@IOKSWc@MOOQ{@y@UK[Si@SSIiA_@}Aa@i@MgC}@}@c@y@_@sDsBaB{@oAq@y@k@wKgGw@_@q@[wBiA_@MOI{CiBOOOOCC'},
                'start_location': {'lat': 22.3848622, 'lng': 114.1893535},
                'travel_mode': 'DRIVING'},
               {'distance': {'text': '0.3 km', 'value': 313},
                'duration': {'text': '1 min', 'value': 21},
                'end_location': {'lat': 22.4041087, 'lng': 114.2057322},
                'html_instructions': 'Take exit <b>2D</b> for <b>Tai Po Road</b>/<wbr/><b>大埔公路</b>',
                'maneuver': 'ramp-left', 'polyline': {'points': 'gjvgCgn`xT[CCAQICCUKa@UKGg@YwAgAo@k@wAwACCCCECGCQKWKKE'},
                'start_location': {'lat': 22.4018035, 'lng': 114.204041}, 'travel_mode': 'DRIVING'},
               {'distance': {'text': '91 m', 'value': 91},
                'duration': {'text': '1 min', 'value': 10},
                'end_location': {'lat': 22.4049176, 'lng': 114.2058146},
                'html_instructions': 'Merge onto <b>Tai Po Road (Ma Liu Shui)</b>',
                'maneuver': 'merge', 'polyline': {'points': 'uxvgCyx`xTS?U@K?KAG@IAKAICQEO?UC'},
                'start_location': {'lat': 22.4041087, 'lng': 114.2057322},
                'travel_mode': 'DRIVING'},
               {'distance': {'text': '1.0 km', 'value': 1028},
                'duration': {'text': '1 min', 'value': 85},
                'end_location': {'lat': 22.4110174, 'lng': 114.2098354},
                'html_instructions': 'At the roundabout, take the <b>2nd</b> exit and stay on <b>Tai Po Road (Ma Liu Shui)</b><div style="font-size:0.9em">Go through 1 roundabout</div>',
                'maneuver': 'roundabout-left',
                'polyline': {'points': 'w}vgCiy`xTA@A@A??@A?A??@A?A?A?A?A?A?A?A?AAA?AAA?AAAAAA?AA??A?AA??A?A?AAA?A?A?A@C?A?A?A@A?A?A@??A@A@AMc@GUCKAQEi@AUCOCOISIS_@q@CCMQQUGGGGKOOUU_@ABEBC@E@CAA?A??AA?AAA??AA??A?AA?AG?C@E?CBC@CBAOy@[yACSI[Mc@CKIOKOQSKOOMOKMGYKWIeCc@WIMEOGYMWKe@Us@YWK[GKAKAK?K?M@OBIBE@OFSHC@QPY\\_@^WPWNMFm@Te@V'},
                'start_location': {'lat': 22.4049176, 'lng': 114.2058146}, 'travel_mode': 'DRIVING'},
               {'distance': {'text': '0.3 km', 'value': 285}, 'duration': {'text': '1 min', 'value': 27},
                'end_location': {'lat': 22.412956, 'lng': 114.208661},
                'html_instructions': 'At the roundabout, take the <b>2nd</b> exit and stay on <b>Tai Po Road (Ma Liu Shui)</b>',
                'maneuver': 'roundabout-left',
                'polyline': {'points': '{cxgCoraxT@@?@?@?@?@?@?@?@A@?@A??@A??@A??@A?A?A??@A?AAA?A?AAA??AA??AAA?AAA?A?A?A?A?A@?WCM?oAFK@I@G@MDOFOHGDA@KHIHGHQTeAxAe@n@'},
                'start_location': {'lat': 22.4110174, 'lng': 114.2098354},
                'travel_mode': 'DRIVING'},
               {'distance': {'text': '0.2 km', 'value': 179},
                'duration': {'text': '1 min', 'value': 48},
                'end_location': {'lat': 22.4143469, 'lng': 114.2080046},
                'html_instructions': 'Turn <b>right</b> onto <b>Chung Chi Rd</b>',
                'maneuver': 'turn-right',
                'polyline': {'points': '_pxgCckaxTQOAAAAC?A?C?C@e@VYNC@_@RID}@d@EB_Af@'},
                'start_location': {'lat': 22.412956, 'lng': 114.208661}, 'travel_mode': 'DRIVING'},
               {'distance': {'text': '0.7 km', 'value': 691},
                'duration': {'text': '2 mins', 'value': 133}, 'end_location': {'lat': 22.418498, 'lng': 114.207536}, 'html_instructions': 'At the roundabout, take the <b>2nd</b> exit and stay on <b>Chung Chi Rd</b>', 'maneuver': 'roundabout-left', 'polyline': {'points': 'uxxgC_gaxT@??@?@?@?@A??@?@A??@A?A?A@A??AA?A??AA??AAA?A?AM?M@G?}@Va@R_A`@iAZQCG?CAMCGCGCMIEGCA]a@Y[EGMMECECMEG?GCMEm@SGAC?C?E@A?C@ABORCH?B?@BJFFDDNL@BFHLP?B@@@D@N@LAJAHCDCDGHSNw@`@KDMDU@E?G?O?QAUGMCSMCCEGAEEu@?CA??AECCAQE'}, 'start_location': {'lat': 22.4143469, 'lng': 114.2080046}, 'travel_mode': 'DRIVING'}, {'distance': {'text': '50 m', 'value': 50}, 'duration': {'text': '1 min', 'value': 11}, 'end_location': {'lat': 22.4185299, 'lng': 114.2080246}, 'html_instructions': 'Turn <b>right</b> onto <b>University Ave</b>', 'maneuver': 'turn-right', 'polyline': {'points': 'srygCcdaxTCuAAI'}, 'start_location': {'lat': 22.418498, 'lng': 114.207536}, 'travel_mode': 'DRIVING'}, {'distance': {'text': '0.5 km', 'value': 468}, 'duration': {'text': '1 min', 'value': 77}, 'end_location': {'lat': 22.4198641, 'lng': 114.2067573}, 'html_instructions': 'Turn <b>left</b> onto <b>Central Ave</b><div style="font-size:0.9em">Destination will be on the left</div>', 'maneuver': 'turn-left', 'polyline': {'points': 'yrygCcgaxTWAKACACCAAACAAAGCq@ACA]AEAQC[GQEGEIEEGEKGOGUGWKEAA?IAC?I?EBCDA@?DAF@F?HAPCJCLSTCF?@EJAHAH?@?N?VAd@?f@AvA?F?F?n@?^@l@'}, 'start_location': {'lat': 22.4185299, 'lng': 114.2080246}, 'travel_mode': 'DRIVING'}], 'traffic_speed_entry': [], 'via_waypoint': []}],
      'overview_polyline': {'points': 'amrgC{m}wTVVHv@xAtAJF^DdC_@|Dw@\\EJ@JDHJFHR~AMRWRGAO@uCj@_APc@BSCSIy@y@qBoBaEsD{AqAuAoACK?KPWfCeDr@_ACm@GKmAgAOMsBfCeEjFoAdBGHQOUK}DaDeB_B_@a@EOWSgA_AaA_AaDkDiGkHcB}Bm@_A[o@iAiCiAsCoBkEc@w@]a@{@y@UKeAg@}Ai@gCo@gC}@}@c@y@_@sDsBqDmBy@k@wKgGiB{@wCwAkDsB_@_@_@GUKgAm@g@YwAgAgCcCUOi@WKES?a@@S?q@Me@CA@C@IBKAIEEIAKDO@CKe@Ka@G{@Ee@Mc@i@eAQUm@u@e@u@GFO@CAECAC?UDGBAOy@_@mBW_AM[]c@[]]Sq@U}Cm@oAg@yAo@s@So@Cm@Jc@PURy@|@o@`@{@\\c@X?@?@?DCFGDG?GECG?E@AWC}AFk@Ji@Xo@r@kBhCSQGAgAh@qDlB@B?@CDEBGCAE[?eAVaBt@iAZQCKAUGUMaAgAYYSIOC{@YKAOBABORCH?DJR^`@P\\B\\CTGJ[XcAf@c@Fo@Ac@KWQGMEy@KGQECuAAIWAKACAIKI{ACWKm@Y]iAc@UCOBEF?TAZGXW\\ELCd@C|G@l@'},
      'summary': 'New Territories Circular Rd/Tai Po Road (Sha Tin)',
      'warnings': [],
      'waypoint_order': []}
